In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.1.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [9]:
import numpy 
l=[1,2,3,4]
arr=numpy.array(l)
arr

array([1, 2, 3, 4])

In [10]:
type(arr)

numpy.ndarray

In [11]:
s1={1,2,[3,4]}
print(s1)

TypeError: unhashable type: 'list'

In [28]:
import numpy as np
a=[1,2,3,4]
ar=np.array(a)
ar


array([1, 2, 3, 4])

In [13]:
type(ar)

numpy.ndarray

In [20]:
type(list(ar))

TypeError: iteration over a 0-d array

In [29]:
ar.tolist()

[1, 2, 3, 4]

In [19]:
type(ar)

numpy.ndarray

In [23]:
t='hello'
arr=np.array(t)
arr

array('hello', dtype='<U5')

In [26]:
arr.tolist()
arr

array('hello', dtype='<U5')

In [30]:
ar*2

array([2, 4, 6, 8])

In [31]:
ar+5

array([6, 7, 8, 9])

In [32]:
ar-1

array([0, 1, 2, 3])

In [33]:
ar/2

array([0.5, 1. , 1.5, 2. ])

In [35]:
n=np.array(ar)
n

array([1, 2, 3, 4])

In [41]:
n1=np.append(n,[6,8,10])
n1


array([ 1,  2,  3,  4,  6,  8, 10])

In [40]:
type(n1)

numpy.ndarray

In [42]:
n1=np.insert(n,3,42)

In [43]:
n1

array([ 1,  2,  3, 42,  4])

In [45]:
n1=np.insert(n,3,(41,42,43))
n1

array([ 1,  2,  3, 41, 42, 43,  4])

In [49]:
n1=np.delete(n,np.where(n==2.0))
n1

array([1, 3, 4])

In [53]:
n1=np.setdiff1d(n,[1.0,2.0])
n1

array([3, 4])

In [52]:
n1=np.delete(n,(1,2))
n1

array([1, 4])

In [54]:
l=[1,2,34,5,6,7,8,45,12]
n=np.array(l)

In [55]:
n

array([ 1,  2, 34,  5,  6,  7,  8, 45, 12])

In [56]:
n<20

array([ True,  True, False,  True,  True,  True,  True, False,  True])

In [57]:
n[n<20]

array([ 1,  2,  5,  6,  7,  8, 12])

In [68]:
n1=n[n<12]
n2=n1[n1>5]
n2


array([6, 7, 8])

In [72]:
n1=(n[n<12])&(n[n>5])
n1

array([0, 2, 5, 0, 5, 8])

In [70]:
(n<12)&(n>5)

array([False, False, False, False,  True,  True,  True, False, False])

In [78]:
n[(n>5)&(n<12)]


array([6, 7, 8])

In [80]:
n[n==12]=15
n

array([ 1,  2, 34,  5,  6,  7,  8, 45, 15])

In [82]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [86]:
np.zeros([3,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [87]:
np.ones(4)

array([1., 1., 1., 1.])

In [92]:
nr=np.ones([3,6])
nr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [89]:
type(n)

numpy.ndarray

In [93]:
nr.dtype

dtype('float64')

In [97]:
nr=np.ones([3,4],dtype=int)

In [98]:
nr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [99]:
nr.dtype

dtype('int32')

In [102]:
nr=np.ones([3,4],dtype='float16')
nr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float16)

In [103]:
nr=np.ones([3,4],dtype='int16')
nr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [104]:
nr=np.ones([3,4],dtype='complex64')
nr

array([[1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j],
       [1.+0.j, 1.+0.j, 1.+0.j, 1.+0.j]], dtype=complex64)

In [106]:
np.int16(nr)

C:\Users\prasa\AppData\Local\Temp\ipykernel_6728\1812825078.py:1: ComplexWarning: Casting complex values to real discards the imaginary part
  np.int16(nr)


array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)