In [1]:
#To print range of values
import numpy as np
ar=np.arange(0,5)
ar

array([0, 1, 2, 3, 4])

In [2]:
#To print range of values with difference of 2
import numpy as np
ar=np.arange(0,5,2)
ar

array([0, 2, 4])

In [3]:
#To print range of values with difference of 3
import numpy as np
ar=np.arange(0,10,3)
ar

array([0, 3, 6, 9])

In [4]:
#converting list into array
l=[1,2,3,4,5,6,7,8,9]
arr=np.array(l)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
#converting 1d array to 2d array
n=arr.reshape(3,3)
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
#creating identity matrix
n1=np.identity(3, dtype=int)
n1

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [12]:
#craeting identity matrix
n2=np.identity(4)
n2

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:
#creating multidimensional array
s1=[1,2,3,4,5]
s2=[6,7,8,9,10]
ar=np.array([s1,s2])
ar

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [30]:
#slicing in multidimensional array
ar[1,1:4]


array([7, 8, 9])

In [4]:
import numpy as np
y=[1,2,3,4,5,6,7,8,9,10,11,12,13]
x=np.array(y)
x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [5]:
x.reshape(13,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13]])

In [12]:
#mean of an array
np.mean(x)

7.0

In [6]:
#median of an array
m=np.median(x)
m

7.0

In [14]:
#sum of an array
np.sum(x)

91

In [15]:
#standard deviation of an array
np.std(x)

3.7416573867739413

In [9]:
#variance of an array
#median by total no of elements
l=len(x)
v=m/l
v

0.5384615384615384

In [16]:
# #linspace
# it is used print the evenly separated numbers b/w to range of values
np.linspace(1,10,5,dtype=int)

array([ 1,  3,  5,  7, 10])

In [15]:
np.linspace(2,20,4,dtype=int)

array([ 2,  8, 14, 20])

In [46]:
# #random module
# it print an random value
#syntax= np.random.randint(start,end)
np.random.randint(1,66,2)

array([35, 51])

In [55]:
# rand()
# it is used to generate values from particular range based on uniformly distributed
np.random.rand(5,3)

array([[0.48593169, 0.95855412, 0.33261631],
       [0.43871016, 0.99533365, 0.43313155],
       [0.43962736, 0.86083956, 0.57396025],
       [0.05685508, 0.66568608, 0.36401429],
       [0.48660674, 0.7847916 , 0.32418713]])

In [56]:
x.max()

13

In [57]:
x.min()

1

In [62]:
ln=[23,45,67,78,43,56,47]
w=ln.index(67)
w

2

In [63]:
nr=np.array(ln)
nr

array([23, 45, 67, 78, 43, 56, 47])

In [67]:
#max in array
max=nr.argmax()
max

3

In [71]:
min=nr.argmin()
min

0

In [70]:
i1=np.where(nr==67)
i1

(array([2], dtype=int64),)

In [73]:
np.cos(nr)/np.sin(nr)

array([ 0.62966222,  0.61736962,  0.60521065, -1.66894757, -0.66738418,
       -1.63592842, -8.03035035])

# 

In [100]:
# multiplication of arrays
a1=np.array([1,2,3,7])
a2=np.array([4,5,6])
l1=len(a1)
l2=len(a2)
l1,l2
if l1>l2:
    l=l1-l2
    i=0
    while(i<l):
        a4=np.append(a2,1)
        i=i+1
    a3=(a1*a4)
else:
    l=l2-l1
    i=0
    while(i<l):
        a4=np.append(a1,1)
        i=i+1
    a3=(a1*a4)
a3

array([ 4, 10, 18,  7])

In [101]:
np.sum(a3)

39

In [3]:
#pandas

In [4]:
pip install pandas

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 23.1.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
#pandas
import numpy as np
import pandas as pd
labels=['a','b','c']
my_data=[10,20,30]
arr=np.array(my_data)
d={"a":100,"b":200,"c":300}
pd.Series(my_data)

0    10
1    20
2    30
dtype: int64

In [7]:
type(pd.Series(my_data))

pandas.core.series.Series

In [8]:
#series with data
pd.Series(my_data)

0    10
1    20
2    30
dtype: int64

In [9]:
#series with labels
pd.Series(data=my_data,index=labels)

a    10
b    20
c    30
dtype: int64

In [16]:
pd.Series(data=my_data,index=labels,dtype=float,name='prasad')

a    10.0
b    20.0
c    30.0
Name: prasad, dtype: float64

In [20]:
sr1=pd.Series([1,2,3,4,5],['USA','INDIA','CANADA','UK','EGYPT'])
sr1

USA       1
INDIA     2
CANADA    3
UK        4
EGYPT     5
dtype: int64

In [21]:
#access values using index
sr1[0:3]

USA       1
INDIA     2
CANADA    3
dtype: int64

In [31]:
sr2=pd.Series([6,7,8],['SA','AUS','NZ'])
sr1+sr2

AUS      NaN
CANADA   NaN
EGYPT    NaN
INDIA    NaN
NZ       NaN
SA       NaN
UK       NaN
USA      NaN
dtype: float64

In [28]:
sr2

SA     6
AUS    7
NZ     8
dtype: int64

In [26]:
#to create new data in series
sr2['china']=4
sr2

SA       1
AUS      2
NZ       3
china    4
dtype: object

In [33]:
#Dataframe
#pd.DataFrame(datas,row _label,col_label)
df=pd.DataFrame(np.random.rand(5,4))
df

0         1         2         3
0  0.171584  0.350118  0.675212  0.833130
1  0.543784  0.143372  0.039494  0.316847
2  0.084771  0.718992  0.865746  0.747591
3  0.405454  0.278478  0.947636  0.027132
4  0.457723  0.432174  0.698115  0.043231

In [50]:
df=pd.DataFrame(np.random.rand(5,4),['a','b','c','d','e'],['w','x','y','z'])
df

w         x         y         z
a  0.282681  0.203761  0.688190  0.066383
b  0.617469  0.708289  0.155903  0.032856
c  0.940931  0.230740  0.170918  0.104095
d  0.817212  0.309493  0.840549  0.982833
e  0.883493  0.508611  0.672262  0.694234

In [48]:
d={'name':['prasad','rohith','varma'],'rno':[42,50,41],'branch':['cst','cst','cst']}
d

{'name': ['prasad', 'rohith', 'varma'],
 'rno': [42, 50, 41],
 'branch': ['cst', 'cst', 'cst']}

In [49]:
df=pd.DataFrame(d,[1,2,3])
df

name  rno branch
1  prasad   42    cst
2  rohith   50    cst
3   varma   41    cst

In [51]:
df

w         x         y         z
a  0.282681  0.203761  0.688190  0.066383
b  0.617469  0.708289  0.155903  0.032856
c  0.940931  0.230740  0.170918  0.104095
d  0.817212  0.309493  0.840549  0.982833
e  0.883493  0.508611  0.672262  0.694234

In [52]:
#to convert colum to row and row to colum
df.T

a         b         c         d         e
w  0.282681  0.617469  0.940931  0.817212  0.883493
x  0.203761  0.708289  0.230740  0.309493  0.508611
y  0.688190  0.155903  0.170918  0.840549  0.672262
z  0.066383  0.032856  0.104095  0.982833  0.694234

In [53]:
#to get row names
df.index

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [55]:
#to get colum names
df.columns

Index(['w', 'x', 'y', 'z'], dtype='object')

In [56]:
type(df)

pandas.core.frame.DataFrame

In [61]:
df.dtypes

w    float64
x    float64
y    float64
z    float64
dtype: object

In [62]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, a to e
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   w       5 non-null      float64
 1   x       5 non-null      float64
 2   y       5 non-null      float64
 3   z       5 non-null      float64
dtypes: float64(4)
memory usage: 372.0+ bytes


In [63]:
df.values

array([[0.28268094, 0.2037606 , 0.68818955, 0.06638349],
       [0.61746871, 0.70828897, 0.15590298, 0.0328561 ],
       [0.94093089, 0.23073995, 0.17091817, 0.10409489],
       [0.81721158, 0.30949321, 0.84054915, 0.98283299],
       [0.88349342, 0.50861054, 0.67226232, 0.69423352]])

In [64]:
df.size

20

In [65]:
# To access specific column in df
df['w']

a    0.282681
b    0.617469
c    0.940931
d    0.817212
e    0.883493
Name: w, dtype: float64

In [66]:
# To access specific multipile columns in df
df[['w','x','y']]

w         x         y
a  0.282681  0.203761  0.688190
b  0.617469  0.708289  0.155903
c  0.940931  0.230740  0.170918
d  0.817212  0.309493  0.840549
e  0.883493  0.508611  0.672262

In [68]:
df['n']=df['w']+df['x']
df['n']

a    0.486442
b    1.325758
c    1.171671
d    1.126705
e    1.392104
Name: n, dtype: float64

In [69]:
df

w         x         y         z         n
a  0.282681  0.203761  0.688190  0.066383  0.486442
b  0.617469  0.708289  0.155903  0.032856  1.325758
c  0.940931  0.230740  0.170918  0.104095  1.171671
d  0.817212  0.309493  0.840549  0.982833  1.126705
e  0.883493  0.508611  0.672262  0.694234  1.392104

In [74]:
df.drop('n',axis=1,inplace=True)
df

w         x         y         z
a  0.282681  0.203761  0.688190  0.066383
b  0.617469  0.708289  0.155903  0.032856
c  0.940931  0.230740  0.170918  0.104095
d  0.817212  0.309493  0.840549  0.982833
e  0.883493  0.508611  0.672262  0.694234

In [75]:
df

w         x         y         z
a  0.282681  0.203761  0.688190  0.066383
b  0.617469  0.708289  0.155903  0.032856
c  0.940931  0.230740  0.170918  0.104095
d  0.817212  0.309493  0.840549  0.982833
e  0.883493  0.508611  0.672262  0.694234